version: '3.3'
services:
  train_perlin:
    build:
      context: .
      target: perlin
    mem_limit: 256MB
    cpus: 0.1
    volumes:
      - ./models:/app/models
  server:
    build:
      context: .
      target: server
    mem_limit: 128MB
    cpus: 0.1
    ports:
      - 8000:3000
    volumes:
      - ./models:/app/models