version: '3.3'
volumes:
  models:
services:
  train_1:
    build:
      context: .
      target: perlin
    volumes:
      - models:/app/models
      - ./outputs:/app/outputs
    environment:
      CONFIG: 404951133
  train_2:
    build:
      context: .
      target: perlin
    volumes:
      - models:/app/models
      - ./outputs:/app/outputs
    environment:
      CONFIG: 558321357
  train_3:
    build:
      context: .
      target: perlin
    volumes:
      - models:/app/models
      - ./outputs:/app/outputs
    environment:
      CONFIG: 1897916942
  train_4:
    build:
      context: .
      target: perlin
    volumes:
      - models:/app/models
      - ./outputs:/app/outputs
    environment:
      CONFIG: 3318148023
  train_5:
    build:
      context: .
      target: perlin
    volumes:
      - models:/app/models
      - ./outputs:/app/outputs
    environment:
      CONFIG: 3492005018