const fs = require('fs');
const path = require('path');
const highResDir = '/content/drive/MyDrive/ia-projects/resolution/high-resolution';
const lowResDir = '/content/drive/MyDrive/ia-projects/resolution/low-resolution';
const modelsDir = '/content/drive/MyDrive/ia-projects/resolution/models';
const tf = require('@tensorflow/tfjs-node');
const stringHash = require('string-hash');
const Network = require('../../Networks/Network');
const epochs = 500;

let configs = [
    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu',poolSize:[2,2]},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu',poolSize:[2,2]},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu',poolSize:[2,2]},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu',poolSize:[2,2]},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'}
        ],
        batchSize:1,
        optimizer:'adam'
    },
    
    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:12},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    }, 

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:16},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:16},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:32},
            {type:'conv2d',filters:16},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:64},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:16},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:16},
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:4},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },
    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:12},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },
    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },
    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:16},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:4},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            'dense',
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },


    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'conv2d',filters:32},
            {type:'conv2d',filters:32},
            {type:'conv2d',filters:3},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'upSampling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'conv2d',filters:3},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:3},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'upSampling2d'},
            {type:'conv2d',filters:6},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3},
            {type:'upSampling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:16},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:16},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:32},
            {type:'conv2d',filters:64},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:64},
            {type:'conv2d',filters:32},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:128},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:32,activation:'softmax'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:64,activation:'softmax'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:32,activation:'softmax'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'softmax'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:8},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'maxPooling2d'},
            {type:'upSampling2d'},
            {type:'dense',activation:'relu',units:8},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'maxPooling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8},
            {type:'upSampling2d'},
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
            {type:'upSampling2d'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'},
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:64,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'}
        ],
        batchSize:1,
        optimizer:'adam'
    },

    {
        inputShape:[128,128,3],
        outputShape:[2048,2048,3],
        layers:[
            {type:'conv2d',filters:8,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:16,activation:'relu'},
            {type:'upSampling2d'},
            {type:'upSampling2d'},
            {type:'conv2d',filters:3,activation:'relu'}
        ],
        batchSize:1,
        optimizer:'adam'
    }
];

async function train(){
    if(!fs.existsSync(highResDir)){
        fs.mkdirSync(highResDir,{recursive:true});
    }

    if(!fs.existsSync(lowResDir)){
        fs.mkdirSync(lowResDir,{recursive:true});
    }

    if(!fs.existsSync(modelsDir)){
        fs.mkdirSync(modelsDir,{recursive:true});
    }

    for(let i = 0; i < configs.length;i++){
        let config = configs[i];
        let id = String(stringHash(JSON.stringify(config)));
        let modelDir = path.join(modelsDir,id);
     
        let net = new Network(config);        
        await net.load(modelDir);
        let data =  fs
            .readdirSync(lowResDir)
            .filter((f) => fs.existsSync(path.join(highResDir,f)))
            .map((f) => path.join(lowResDir,f))
            .map(function(f){
                return [
                    f,
                    path.join(highResDir,path.basename(f))
                ];
            })
            .slice(0,1);

        let dataset = tf.data.array(data).map(function(e){
            return {
                xs: tf.node.decodeImage(fs.readFileSync(e[0])),
                ys: tf.node.decodeImage(fs.readFileSync(e[1]))
            };
        });
    
        await net.train(dataset,epochs,async function(epoch,epochs,loss,acc){
            console.log(`${epoch}/${epochs} loss:${loss}, accuracy:${acc}`);
        });
        
        await net.save(modelDir);
    }
};

(async function(){
    let finished = false;
    do{
        try{
            await train();
            finished = true;
        }
        catch(e){
    
        }
    }
    while(!finished);
})();